sonar.projectKey=collector-shop
sonar.projectName=collector-shop
sonar.projectVersion=1.0

sonar.sources=backend/src/main,frontend/src
sonar.tests=backend/src/test,frontend/tests

sonar.java.binaries=backend/target/classes
sonar.junit.reportPaths=backend/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/coverage/**,**/test-results/**